### ISSUE TITLE
auxiliaryApps parameter giving error

### ISSUE THREAD

**Issue by JigneshArtoo** [artemnikitin/devicefarm-ci-tool#77]
Hi,
Thank you for sharing this repo, it's very useful.

I am getting error for auxiliaryApps parameter. I am putting local path to APKs in auxiliaryApps but is giving following error

validator.go:8: Failed to run tests: ValidationException: 1 validation error detected: Value '[extra/app1.apk, extra/app2.apk]' at 'configuration.auxiliaryApps' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 1011, Member must have length greater than or equal to 32]

Can you please help on the same.

Thanking you in advance,
Jignesh

**Comment by artemnikitin** [comment]
Sure, I will look into it

**Comment by artemnikitin** [comment]
Looks like your path to the auxiliary app is too short. https://docs.aws.amazon.com/devicefarm/latest/APIReference/API_ScheduleRunConfiguration.html

Try to rename it from `extra/app1.apk` to something like `extra/test-app1-svsfsdsdfsdf.apk`. You need to have at least 32 symbols length.

**Comment by JigneshArtoo** [comment]
Hi,
Thank you for your reply.

I tried the same but now its giving following error:
Failed to run tests: ArgumentException: Invalid Upload arn:<local_path_to_APK>

I guess `auxiliaryApps` is expecting ARN and not local APKs. Is there any way we can upload local  APKs in `auxiliaryApps`?

Regards,
Jignesh

**Comment by artemnikitin** [comment]
@JigneshArtoo I found an issue. Working on a fix now.

**Comment by artemnikitin** [comment]
Issue was fixed in https://github.com/artemnikitin/devicefarm-ci-tool/releases/tag/1.4. Please grab latest binary and run it like:
```
devicefarm-ci-tool -project name -app /path/to/my/app.apk -config path/to/config.json
```
`config.json` should contain line `"auxiliaryAppsPath": [ "path/to/app-1", "path/to/app-2" ],`
